services:
  nas-dash:
    image: ghcr.io/taranjotwani/nas-dashboard:latest
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      MUSIC_DIR: /data/music
    volumes:
      - type: bind
        source: ${MUSIC_SOURCE_DIR:-./music}
        target: /data/music