/**
 * Link schema definition.
 * This object describes the structure and validation rules for a link document
 * stored in MongoDB. Update this file to change field definitions.
 */

const LINK_SCHEMA = {
  /**
   * Unique identifier — generated by MongoDB (_id) and mirrored as `id`
   * using a UUID string for API compatibility.
   */
  id: {
    type: 'string',
    required: true,
    description: 'UUID v4 string, serves as the public identifier'
  },

  /** Display name shown on the dashboard tile */
  name: {
    type: 'string',
    required: true,
    maxLength: 200,
    description: 'Human-readable label for the link'
  },

  /** Destination URL — must be http or https */
  url: {
    type: 'string',
    required: true,
    description: 'Fully-qualified http/https URL'
  },

  /** ISO-8601 timestamp set when the document is first created */
  createdAt: {
    type: 'string',
    required: true,
    description: 'Creation timestamp (ISO 8601)'
  },

  /** ISO-8601 timestamp updated on every PUT — undefined on new documents */
  updatedAt: {
    type: 'string',
    required: false,
    description: 'Last-updated timestamp (ISO 8601)'
  }
};

/**
 * Build a new link document ready for insertion.
 * @param {string} id   - UUID string
 * @param {string} name - Validated display name
 * @param {string} url  - Validated URL string
 * @returns {{ id: string, name: string, url: string, createdAt: string }}
 */
function createLinkDocument(id, name, url) {
  return {
    id,
    name,
    url,
    createdAt: new Date().toISOString()
  };
}

/**
 * Build an updated link document by merging existing fields with new values.
 * @param {object} existing   - The current document from the database
 * @param {string} name       - New display name
 * @param {string} url        - New URL
 * @returns {object}
 */
function updateLinkDocument(existing, name, url) {
  return {
    ...existing,
    name,
    url,
    updatedAt: new Date().toISOString()
  };
}

/**
 * MongoDB index definitions for the links collection.
 * Each entry maps directly to a createIndex() call.
 */
const LINK_INDEXES = [
  { key: { id: 1 }, options: { unique: true, name: 'id_unique' } },
  { key: { createdAt: 1 }, options: { name: 'createdAt_asc' } }
];

module.exports = { LINK_SCHEMA, LINK_INDEXES, createLinkDocument, updateLinkDocument };
